baseURL = "https://tuff-studio.com/"
languageCode = "UTF-8"
title = "Tuff Studio, Freelance Web Developer"
theme = "tuff"
disableKinds = ["taxonomy", "term"]
disablePathToLower = true

[params]
  description = "I make websites and web apps. Based in London and Europe."
